stages:
  - build

build-frontend:
  stage: build
  image: node:18.17.1
  cache:
    key:
      prefix: 'frontend'
      files:
        - 'package-lock.json'
    paths:
      - 'node_modules'
  before_script:
    - 'npm ci'
  script:
    - 'npm run build'
  artifacts:
    name: 'frontend-${CI_COMMIT_SHORT_SHA}'
    paths:
      - 'dist'
